<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <InternalsVisibleTo Include="EMS.Application.UnitTests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EMS.Domain\EMS.Domain.csproj" />
    <ProjectReference Include="..\Pukar.Notifications\Pukar.Notifications.Application\Pukar.Notifications.Application.csproj" />
    <ProjectReference Include="..\Pukar.Usermanagement\Pukar.Shared\Pukar.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.105.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.4" />
    <PackageReference Include="QuestPDF" Version="2026.2.4" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
